"""empty message

Revision ID: a5f81010110a
Revises: 
Create Date: 2019-07-08 20:23:22.549971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f81010110a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('contact_phone', sa.String(length=9), nullable=True),
    sa.Column('company_label', sa.String(length=128), nullable=True),
    sa.Column('artist_band', sa.String(length=128), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('address_1', sa.String(length=128), nullable=True),
    sa.Column('address_2', sa.String(length=128), nullable=True),
    sa.Column('address_city', sa.String(length=64), nullable=True),
    sa.Column('address_state', sa.String(length=64), nullable=True),
    sa.Column('address_postal_code', sa.String(length=64), nullable=True),
    sa.Column('address_country', sa.String(length=64), nullable=True),
    sa.Column('additional_comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
